---
- name: Disable the DNS stub listener
  lineinfile:
    dest: /etc/systemd/resolved.conf
    regexp: "^#?DNSStubListener=yes"
    line: "DNSStubListener=no"

- name: Remove the existing symlink
  file:
    path: /etc/resolv.conf
    state: absent

- name: Point a new symlink to the other file
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
    name: "{{ container_name }}"
    image: pihole/pihole:2023.05.2
    hostname: "{{ inventory_hostname }}"
    domainname: pihole.box
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
      "WEBPASSWORD": "{{ pihole_password }}"
      "FTLCONF_REPLY_ADDR4": "{{ ansible_default_ipv4.address }}"
      "REV_SERVER": "true"
      "REV_SERVER_DOMAIN": "box"
      "REV_SERVER_TARGET": "{{ ansible_default_ipv4.gateway }}"
      "REV_SERVER_CIDR": "{{ '.'.join(ansible_default_ipv4.address.split('.')[0:3]) }}.0/24"
      "DNSSEC": "true" # Enable DNSSEC
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/pihole:/etc/pihole"
      - "{{ docker_dir }}/{{ container_name }}/dnmasq:/etc/dnsmasq.d"
    ports:
      - "81:80/tcp"
      - "{{ ansible_default_ipv4.address }}:53:53/tcp"
      - "{{ ansible_default_ipv4.address }}:53:53/udp"
    restart_policy: unless-stopped