---
- name: Get info on the SWAG containers
  docker_container_info:
    name: "swag_internal"
  register: swag_docker_status
  # with_items:
  #   - swag_internal
  #   - swag_public

- name: Do containers exist?
  set_fact:
    existing: yes
  when: swag_docker_status.exists

- name: Are containers running?
  set_fact:
    running: yes
  when: existing is defined and swag_docker_status.container['State']['Running']