username: ubuntu

packages:
  - nginx

snaps:
  - btop

hostname: "{{ inventory_hostname }}"

timezone: Australia/Queensland

locale: en_US.UTF-8

dot_nameservers: [1.1.1.1, 1.0.0.1]

lan_network: 192.168.50.0/24

# Link to .zshrc file (GitHub raw)
zshrc_url: https://raw.githubusercontent.com/xMdb/dotfiles/main/.zshrc

# Link to .p10k.zsh (Powerline10k theme config) file (GitHub raw) 
p10k_config_url: https://raw.githubusercontent.com/xMdb/dotfiles/main/.p10k.zsh

docker_dir: /opt/docker/data