- name: test nginx
  command:
    cmd: docker exec -it swag_internal /usr/sbin/nginx -c /config/nginx/nginx.conf -t
  register: swag_nginx_test
  changed_when: swag_nginx_test is not search("test is successful")
  failed_when: swag_nginx_test is not search("test is successful")
  # with_items:
  #   - swag_internal
  #   - swag_public

- name: restart swag
  docker_container:
    name: swag_internal
    state: started
    restart: yes
  # with_items:
  #   - swag_internal
  #   - swag_public
  when: existing is defined and running is defined