---
- name: Create the configuration directory
  file:
     path: '{{ docker_dir }}/{{ container_name }}/data/'
     state: directory
     recurse: yes

- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
     name: wakapi
     image: ghcr.io/muety/wakapi:latest
     state: 'started'
     env:
        WAKAPI_INSECURE_COOKIES: 'false'
        WAKAPI_ALLOW_SIGNUP: 'false'
        WAKAPI_MAIL_ENABLED: 'false'
     volumes:
        - '{{ docker_dir }}/{{ container_name }}/data:/data'
     ports:
        - '3000:3000'
     restart_policy: unless-stopped
