---
- name: Stop and disable the existing DNS service
  service:
    name: systemd-resolved.service
    state: stopped

- name: Change default DNS server
  lineinfile:
    dest: /etc/resolv.conf
    regexp: "^nameserver (.+)"
    line: "nameserver 1.1.1.1"

- name: Create the configuration directory
  file:
    path: "{{ docker_dir }}/{{ container_name }}/unbound.conf.d/"
    state: directory
    recurse: yes

- name: Copy the unbound configuration file
  template:
    src: unbound.j2
    dest: "{{ docker_dir }}/{{ container_name }}/unbound.conf.d/pi-hole.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
    name: 'pihole'
    image: "cbcrowe/pihole-unbound"
    privileged: yes
    hostname: "{{ inventory_hostname }}"
    domainname: pihole.local
    pull: false
    state: 'started'
    env:
      "ServerIP": "{{ ansible_default_ipv4.address }}"
      "TZ": "{{ timezone }}"
      "WEBPASSWORD": "{{ pihole_password }}"
      "REV_SERVER": "true"
      "REV_SERVER_DOMAIN": "local"
      "REV_SERVER_TARGET": "{{ ansible_default_ipv4.gateway }}"
      "REV_SERVER_CIDR": "{{ '.'.join(ansible_default_ipv4.address.split('.')[0:3]) }}.0/24"
      "DNS1": "127.0.0.1#5335" # Hardcoded to our Unbound server
      "DNS2": "127.0.0.1#5335" # Hardcoded to our Unbound server
      "DNSSEC": "true" # Enable DNSSEC
      "DOMAIN_NAME": "pihole.local"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/pihole:/etc/pihole"
      - "{{ docker_dir }}/{{ container_name }}/dnmasq-unbound:/etc/dnsmasq.d"
      - "{{ docker_dir }}/{{ container_name }}/unbound.conf.d/pi-hole.conf:/etc/unbound/unbound.conf.d/pi-hole.conf"
    ports:
      - "81:80/tcp"
      - "{{ ansible_default_ipv4.address }}:53:53/tcp"
      - "{{ ansible_default_ipv4.address }}:53:53/udp"
    restart_policy: unless-stopped