---
- name: Create Firefly III Directories
  file:
     path: '{{ item }}'
     state: directory
  with_items:
     - '{{ docker_dir }}/firefly/postgresql'
     - '{{ docker_dir }}/firefly/mysql'
     - '{{ docker_dir }}/firefly/upload'
     - '{{ docker_dir }}/firefly/export'

- name: Create MariaDB container for Firefly
  docker_container:
     name: firefly-db
     image: mariadb
     hostname: fireflyiiidb
     pull: false
     volumes:
        - '{{ docker_dir }}/firefly/mysql:/var/lib/mysql:rw'
     env:
        MYSQL_DATABASE: 'firefly'
        MYSQL_USER: 'firefly'
        MYSQL_PASSWORD: 'firefly'
        MYSQL_ROOT_PASSWORD: 'firefly'
     restart_policy: always
     state: 'started'

- name: Wait for MariaDB to init
  pause:
     seconds: 5

- name: Make sure the Firefly III container is created and is running
  docker_container:
     name: firefly
     image: fireflyiii/core:latest
     volumes:
        - '{{ docker_dir }}/firefly/export:/var/www/html/storage/export:rw'
        - '{{ docker_dir }}/firefly/upload:/var/www/html/storage/upload:rw'
     links:
        - firefly-db:db
     ports:
        - 1001:8080
     domainname: firefly.local
     pull: false
     state: 'started'
     env:
        APP_ENV: 'local'
        APP_KEY: '{{ firefly_api_key }}'
        DB_CONNECTION: 'mysql'
        DB_HOST: 'db'
        DB_DATABASE: 'firefly'
        DB_USERNAME: 'firefly'
        DB_PASSWORD: 'firefly'
        TZ: '{{ timezone }}'
        TRUSTED_PROXIES: '**'
     restart_policy: unless-stopped
